spring:
  resources:
    static-locations: classpath:/static/
  devtools:
    restart:
      log-condition-evaluation-delta: false
  datasource:
    url: jdbc:mysql://localhost:3306/goshop
    username: root
    password: root
  jpa:
    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always


twilio:
  accountSid: ACafd4d89b5fcf368f857c56cfeb125288
  authToken: 911ee2c2c5925c7e1d3e07005a55abcf
  phone:
    number: +13614540810


firebase:
  config:
    path: classpath:firebase-config.json
  project:
    id: go-shop-java

logging:
  level:
    web: debug