spring:
  resources:
    static-locations: classpath:/static/
  devtools:
    restart:
      log-condition-evaluation-delta: false
  datasource:
    url: jdbc:mysql://localhost:3306/goshop
    username: root
    password: root
  jpa:
    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always


