spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goshop
    username: root
    password: root
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  resources:
    static-locations: classpath:/static/
  devtools:
    restart:
      log-condition-evaluation-delta: false

#    show-sql: true
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

server:
  error:
    path: /error
    whitelabel:
      enabled: false

twilio:
  accountSid: ACafd4d89b5fcf368f857c56cfeb125288
  authToken: e3cee72acb3c8727dea7091d83bccbfd
  phone:
    number: +13614540810



logging:
  level:
    web: debug

razorpay:
  keyId: rzp_test_ti4COoTWxp1e7t
  keySecret: lresCW3FKCaaVJxwo8THLWxk